language: cpp

dist: trusty
sudo: required

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cppcheck
            - valgrind
      env:
        - CC=gcc-7
        - CXX=g++-7

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - libstdc++-7-dev
            - clang-5.0
            - cppcheck
            - valgrind
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0

before_install:
    - sudo wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp -O /usr/include/catch.hpp

install: true

script: ./build.sh
