language: cpp

dist: trusty
sudo: required

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-9
            - llvm-8-dev
            - cppcheck
            - valgrind
      env:
        - CC=gcc-9
        - CXX=g++-9

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
            - llvm-8-dev
            - libstdc++-8-dev # since [libc++](https://libcxx.llvm.org/)'s C++17 implementation is not yet complete.
            - cppcheck
            - valgrind
      env:
        - CC=clang-8
        - CXX=clang++-8

before_install:
    - sudo wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp -O /usr/include/catch.hpp

install: true

script: ./build.sh
